version: 2
jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run: 
          name: Updating Package List
          command: apt-get update
      - run:
          name: Installing Build Tools
          command: apt-get install -y gcc g++ make
      - run:
          name: Installing htslib
          command: apt-get install -y libhts1 libhts-dev
      - run:
          name: Run Make
          command: 'make clean && make'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
